@startuml

folder "models" {
    database "DB" {
        
    }
}

folder "modules" {
    [some thing that could be a library]
}

folder "services" {
    [git code]
}

folder "web_src" {
    file "some web source"
}

folder "routers" {
    [API]
    [web routes]
}

folder "templates" {
    file "go template file"
}

folder "tests" {
    [integration tests]
}

[services] -> [models]
[services] -> [modules]

[routers] -> [services]
[routers] -> [modules]
[routers] -> [models]
[routers] -> [web_src]
[routers] -> [templates]

[tests] -> [models]
[tests] -> [modules]
[tests] -> [services]
[tests] -> [web_src]
[tests] -> [routers]
[tests] -> [templates]

@enduml
